# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false


# https://github.com/rails/rubocop-rails-omakase/blob/main/rubocop.yml#L224
Style/StringLiterals:
  Enabled: false
